# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acPiUC-ikr5RDgyHFFv36RqfEPsz34nW
"""

def soz_nomi(sozni_kiriting):
   if sozni_kiriting=="olma":
    return "apple"
   elif sozni_kiriting=="qovun":
    return "melon"
   if sozni_kiriting==" tarvuz":
    return "watermelon"
   if sozni_kiriting=="qulupnay ":
    return "strawberry"
   if sozni_kiriting=="olcha":
    return "cherry "
   if sozni_kiriting=="shaftoli":
    return "peach"
   else:
    return "bazada bunday meva mavjud emas"
sozni_kiriting=input ("sozni kiriting")
natija=soz_nomi(sozni_kiriting)
print(natija)